#!/bin/sh

# In W
MAX_TDP=265
# In MHz
MAX_CLOCK=2035
# In mV
MAX_VOLT=1150

GPU=$(glxinfo -B | awk -F: '/OpenGL renderer string/{print $2}' | awk -F'(' '{print $1}' | xargs)

! echo "$GPU" | grep "AMD\|Radeon\|RX" && {
	echo "GPU is not currently supported."
	exit 1
}

line=$(grep "$GPU" ./gpus.csv)

get_info()
{
	echo "$line" | awk -F',' "{print $1}"
}

# Set conservative defaults for a GPU overclock if overclock parameters aren't
# defined.
[ -z "$MAX_TDP" ] && MAX_TDP=$(get_info 4)
[ -z "$MAX_CLOCK" ] && MAX_CLOCK=$(get_info 2)
[ -z "$MAX_VOLT" ] && MAX_VOLT=$(get_info 3)

# [ "$USER" != "root" ] && {
# 	echo "$0 needs to be run by root."
# 	exit 1
# }

gpu_dir="/sys/class/drm/card0/device"
# gpu_dir="/sys/class/drm/card1/device"

if [ ! -d "$gpu_dir" ]; then
	echo "GPU not correctly configured"
	exit 1
elif [ ! -e "$gpu_dir/pp_od_clk_voltage" ]; then
	if [ -e /etc/default/grub ]; then
		echo "AMDGPU overclocking is not enabled, so enabling now for next boot."
		sudo sed '/GRUB_CMDLINE_LINUX_DEFAULT/ s/"$/ amdgpu.ppfeaturemask=0xffffffff"' /etc/default/grub
		sudo grub-mkconfig -o /boot/grub/grub.cfg
		echo "Would you like to reboot now to enable AMDGPU overclocking? [y/n]"
		read -r reboot_now
		case $reboot_now in
			"y"*|"Y"*)
				echo "Rebooting..."
				reboot
				;;
			*)
				echo "Please reboot to enable AMDGPU overclocking."
				exit 0
				;;
		esac
	else
		echo "Bootloader not recognized."
		echo "Please create an issue in the git repo at https://github.com/durcor/oc to add support for your bootloader."
		echo "Enable AMDGPU overclocking by adding 'amdgpu.ppfeaturemask=0xffffffff' to your boot parameters and reboot."
		exit 1
	fi
fi

overclock()
{
	echo "Changing the TDP of your $GPU to $MAX_TDP W"
	sudo sh -c "echo ${MAX_TDP}000000 > $gpu_dir/hwmon/$(ls $gpu_dir/hwmon)/power1_cap"

	echo "Clocking your $GPU to $MAX_CLOCK MHz @ $MAX_VOLT mV"
	sudo sh -c "echo \"s $(grep -B 1 OD_MCLK $gpu_dir/pp_od_clk_voltage | head -1 | awk -F':' '{print $1}') $MAX_CLOCK $MAX_VOLT\" > $gpu_dir/pp_od_clk_voltage"
	# echo "m $(grep -B 1 "OD_VDDC_CURVE" $gpu_dir/pp_od_clk_voltage | head -1 | awk -F':' '{print $1}') 1850 850" > $gpu_dir/pp_od_clk_voltage
	sudo sh -c "echo c > $gpu_dir/pp_od_clk_voltage"

	echo "Reclock of your $GPU complete!"
}

case $1 in
	"off")
		echo "r" > $gpu_dir/pp_od_clk_voltage
		;;
	"on"|"")
		overclock
		;;
esac
